Algoritmo "Condicao"
// Definir o nome do Programa

Var
// Seção de Declarações das variáveis 
    valor: real
    idade: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor disponível para viagem: ", valor)
leia(valor)

se valor >= 10000 entao
   escreva("Vamos para Disney")
senao
     escreva("Saldo insuficiente")
fimse

se idade >= 18 entao
   escreva("Autorizado a viajar")

senao
     escreva("Não Autorizado a viajar")
fimse
Fimalgoritmo