Algoritmo "Contadorate10"
//
Var
// Seção de Declarações das variáveis 
  valor, salto, contador: Inteiro

Inicio
   contador:= 0
   Escreva("Quer contar ate quanto? ")
                 Leia(valor)
   Escreval("Qual será o valor do salto? ")
                  Leia(salto)
   enquanto (contador <= valor)faca
            escreval(contador)
            contador:= contador + salto
   
   fimenquanto
   escreval("Terminei de contar")
   
Fimalgoritmo
