Algoritmo "Media"

Var
// Seção de Declarações das variáveis 
   numero1,numero2,numero3,media: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite o primeiro número: ")
   Leia(numero1)
   Escreva("Digite o segundo número: ")
   Leia(numero2)
   Escreva("Digite o terceiro número: ")
   Leia(numero3)

   media := numero1 + numero2+numero3/3

    escreva("A média é: ", media)

Fimalgoritmo